### ISSUE TITLE
ofcd数据集如何制作

### ISSUE THREAD

**Issue by wifiBlack** [TangYJ1229/FDINet#1]
您好！在文章中，您说您对WHU的变化检测数据集进行了一定的处理使它满足了OFCD任务的要求，想请教一下作者是通过手动标注的方式对原始的变化检测数据集的Label进行处理的吗？

**Comment by TangYJ1229** [comment]
> 您好！在文章中，您说您对WHU的变化检测数据集进行了一定的处理使它满足了OFCD任务的要求，想请教一下作者是通过手动标注的方式对原始的变化检测数据集的Label进行处理的吗？

感谢您的关注，whu数据集的原始文件中包括两个时相的建筑标签，因此，您可以直接对两幅时相的标签进行处理，不需要手动标注。
